#!/usr/bin/env bash

## Autostart Programs
# Export desktop session
export XDG_CURRENT_DESKTOP='qtile'

# Kill already running process
_ps=(ksuperkey)
for _prs in "${_ps[@]}"; do
	if [[ `pidof ${_prs}` ]]; then
		killall -9 ${_prs}
	fi
done

# polkit agent
# if [[ ! `pidof polkit` ]]; then
# 	polkit &
# fi

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Fix cursor
xsetroot -cursor_name left_ptr

# Restore wallpaper
xwallpaper --output all --zoom $HOME/dotfiles/qtile/wallpaperdark.png

# Launch dunst daemon
if [[ `pidof dunst` ]]; then
	pkill dunst
fi

dunst -config ./dunstrc &

# Lauch compositor
# Terminate if picom is already running
killall -q picom

# Wait until the processes have been shut down
while pgrep -x picom >/dev/null; do sleep 1; done

picom --daemon --config ./picom.conf &

# Start Flameshot
if [[ ! `pidof flameshot` ]]; then
	pkill flameshot
fi
flameshot &
