#!/usr/bin/env bash

## Autostart Programs
# Export desktop session
export XDG_CURRENT_DESKTOP='qtile'

# Kill already running process
_ps=(ksuperkey)
for _prs in "${_ps[@]}"; do
	if [[ $(pidof ${_prs}) ]]; then
		killall -9 ${_prs}
	fi
done

# Start Polkit KDE agent
/nix/store/$(ls -la /nix/store | grep polkit-kde-agent | grep '^d' | awk '{print $9}')/libexec/polkit-kde-authentication-agent-1 &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Fix cursor
xsetroot -cursor_name left_ptr

# set monitor resolution, refresh rate, and placement
xrandr --output DP-2 --mode 1920x1080 --rate 144 --left-of HDMI-1 --primary --preferred --output HDMI-1 --mode 2560x1440 --rate 59.95

# Restore wallpaper
xwallpaper --output all --zoom "$HOME/dotfiles/home-manager/lubyanka/qtile/wallpaperdark.png"

# Launch dunst daemon
if [[ $(pidof dunst) ]]; then
	pkill dunst
fi

dunst -config "$HOME/dotfiles/home-manager/dunstrc" &

# Lauch compositor
# Terminate if picom is already running
killall -q picom

# Wait until the processes have been shut down
while pgrep -x picom >/dev/null; do sleep 1; done

picom --config "$HOME/dotfiles/home-manager/lubyanka/qtile/picom.conf" &

# Start CopyQ
copyq &

# Start Flameshot
if [[ ! $(pidof flameshot) ]]; then
	pkill flameshot
fi
flameshot &
