# Source omarchy base config
source-file ~/.local/share/omarchy/config/tmux/tmux.conf

# Default shell
set-option -g default-shell /usr/bin/zsh

# Override history limit
set -g history-limit 100000

# Move window to pane
bind-key m choose-window -F "#{window_index}: #{window_name}" "join-pane -h -t %%"
bind-key M choose-window -F "#{window_index}: #{window_name}" "join-pane -v -t %%"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'azorng/tmux-smooth-scroll'
set -g @plugin 'christoomyer/vim-tmux-navigator'

# Initialize TMUX plugin manager (keep this line at the very bottom)
run '~/.tmux/plugins/tpm/tpm'
