# Source omarchy base config
source-file ~/.local/share/omarchy/config/tmux/tmux.conf

# Default shell
set-option -g default-shell /usr/bin/zsh

# Override history limit
set -g history-limit 100000

# Theme overrides
set -g status-style "fg=brightblack,bg=default"
set -g window-status-format "  #I:#W  "
set -g window-status-current-format "#[fg=blue,bold]  #I:#W  "
set -g status-left ""
set -g status-left-length 0
set -g status-right "#[fg=brightblack] tmux "
set -g status-right-length 10
set -g message-style "fg=blue,bg=default"
set -g pane-border-lines heavy
set -g pane-border-indicators arrows
set -g pane-border-status top
set -g pane-border-format "[ ###P `#{pane_current_command}` ]"

# Move window to pane
bind-key m choose-window -F "#{window_index}: #{window_name}" "join-pane -h -t %%"
bind-key M choose-window -F "#{window_index}: #{window_name}" "join-pane -v -t %%"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'azorng/tmux-smooth-scroll'
set -g @plugin 'christoomyer/vim-tmux-navigator'

# Initialize TMUX plugin manager (keep this line at the very bottom)
run '~/.tmux/plugins/tpm/tpm'
