$background = rgb(263232)
$foreground = rgb(EEE3AD)
$color0 = rgb(1C2023)
$color1 = rgb(7DA870)
$color2 = rgb(3E787A)
$color3 = rgb(6A90BB)
$color4 = rgb(B07A4F)
$color5 = rgb(C795AE)
$color6 = rgb(DB8A7D)
$color7 = rgb(DEFFAA)
$color8 = rgb(9A71AA)
$color9 = rgb(7DA870)
$color10 = rgb(3E787A)
$color11 = rgb(6A90BB)
$color12 = rgb(B07A4F)
$color13 = rgb(C795AE)
$color14 = rgb(DB8A7D)
$color15 = rgb(F3F4F5)
