#!/usr/bin/env bash

# Import Current Theme
DIR="$HOME/dotfiles/home-manager/rofi"
RASI="$DIR/launcher.rasi"

# Run
rofi \
	-show drun \
	-kb-cancel Alt-F1 \
	-theme "${RASI}" \
	-font "Terminess Nerd Font 16"
