[[manager.prepend_keymap]]
on   = [ "g", "g" ]
run  = "cd /ssd/Games"
desc = "Cd to /ssd/Games"

[[manager.prepend_keymap]]
on   = [ "g", "p" ]
run  = "cd ~/Pictures"
desc = "Cd to ~/Pictures"

[[manager.prepend_keymap]]
on   = [ "g", "v" ]
run  = "cd ~/Videos"
desc = "Cd to ~/Videos"

[[manager.prepend_keymap]]
on   = [ "g", "d" ]
run  = "cd ~/dotfiles"
desc = "Cd to ~/dotfiles"

[[manager.prepend_keymap]]
on   = [ "g", "D" ]
run  = "cd ~/Downloads"
desc = "Cd to ~/Downloads"

[[manager.prepend_keymap]]
on   = [ "g", "w" ]
run  = "cd ~/Work"
desc = "Cd to ~/Work"

[[manager.prepend_keymap]]
on   = [ "g", "G" ]
run  = "cd ~/GitHub"
desc = "Cd to ~/GitHub"

[[manager.prepend_keymap]]
on   = [ "g", "n" ]
run  = "cd /etc/nixos"
desc = "Cd to /etc/nixos"
