# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# This is where you put your own keybinds. Be Mindful to check as well ~/.config/hypr/configs/Keybinds.conf to avoid conflict
# if you think I should replace the Pre-defined Keybinds in ~/.config/hypr/configs/Keybinds.conf , submit an issue or let me know in DC and present me a valid reason as to why, such as conflicting with global shortcuts, etc etc

# See https://wiki.hyprland.org/Configuring/Keywords/ for more settings and variables
# See also Laptops.conf for laptops keybinds 

$mainMod = SUPER
$files = yazi
$term = wezterm
$scriptsDir = $HOME/.config/hypr/scripts
$UserScripts = $HOME/.config/hypr/UserScripts

# rofi App launcher
#bindr = $mainMod, $mainMod_L, exec, pkill rofi || rofi -show drun -modi drun,filebrowser,run,window # Super Key to Launch rofi menu
bind = $mainMod, space, exec, pkill rofi || rofi -show drun -modi drun,filebrowser,run,window

# ags overview
bind = $mainMod, A, exec, pkill rofi || true && ags -t 'overview'

bind = $mainMod SHIFT, Return, exec, $term  # Launch separate terminal
bind = $mainMod SHIFT, T, exec, $term start yazi # Launch separate yazi

bind = $mainMod ALT, C, exec, $UserScripts/RofiCalc.sh # calculator (qalculate)

# pyprland
bind = $mainMod, Return, exec, pypr toggle wezterm # Dropdown terminal
bind = $mainMod, T, exec, pypr toggle yazi # Dropdown yazi
bind = $mainMod, Z, exec, pypr zoom # Toggle Zoom

# Special workspace / scratchpad
bind = $mainMod, grave, togglespecialworkspace, tildespace
bind = $mainMod SHIFT, grave, movetoworkspace, special:tildespace

# For passthrough keyboard into a VM
# bind = $mainMod ALT, P, submap, passthru
#submap = passthru
# to unbind
#bind = $mainMod ALT, P, submap, reset
#submap = reset

# copy and paste script
bind = $mainMod, C, exec, $UserScripts/AutoCopy.sh
#bind = $mainMod, V, exec, $UserScripts/AutoPaste.sh
