[pyprland]

plugins = [
  "scratchpads",
  "magnify",
]

[scratchpads.term]
animation = "fromTop"
command = "foot -a foot-dropterm"
class = "foot-dropterm"
size = "75% 60%"

[scratchpads.yazi]
animation = "fromTop"
command = "foot -a foot-dropyazi yazi"
class = "foot-dropyazi"
size = "75% 60%"
