[pyprland]

plugins = [
  "scratchpads",
  "magnify",
]

[scratchpads.wezterm]
animation = "fromTop"
command = "wezterm start --always-new-process --class wezterm-dropterm"
class = "wezterm-dropterm"
size = "75% 60%"

[scratchpads.yazi]
animation = "fromTop"
command = "wezterm start --always-new-process --class wezterm-dropyazi yazi"
class = "wezterm-dropyazi"
size = "75% 60%"

[scratchpad.nvtop]
animation = "fromTop"
command = "wezterm start --always-new-process --class wezterm-dropnvtop nvtop"
class = "wezterm-dropnvtop"
size = "85% 70%"
